### PR TITLE
Add support for pooled connections + cleanup

### LINKED ISSUE #16: Flooding with warning messages
First of all, thanks for this great library!

When both Configuration and Settings are available then there's a warning logged:
```
if (configuration != null) {
      logger.debug("Creating factory from configuration having dialect {}", configuration.dialect());
      if (jooqSettings != null) {
        logger.warn("@Injected org.jooq.conf.Settings is being ignored since a full org.jooq.Configuration was supplied");
      }
```
Unfortunately Guice is always binding the Settings automatically using the default constructor and I can't get rid of this warning. I tried to declare the Settings as null but then I get `NULL_INJECTED_INTO_NON_NULLABLE` exception.

Could you please either change the log level or add `@Nullable` (https://github.com/google/guice/wiki/UseNullable) annotation to the fields?

Otherwise every transaction logs a warning.

> WARN [JooqPersistService] @Injected org.jooq.conf.Settings is being ignored since a full org.jooq.Configuration was supplied

### PR DESCRIPTION
**Pull request by apptio-msobala**
* reuse acquired connection in transaction configuration
* switch to optional binder for Configuration and Settings
* log warning about ignored Settings on construction only
* bump java to 8, jOOQ to 3.16.4 and Guice to 5.1.0

Fixes #16.

### CODE REVIEW

**Comment by supercargo** [comment]
Awesome, thanks for the PR @apptio-msobala!  This doesn't build as-is for me because it looks like jOOQ 3.15.0 requires Java 11 (at least for the OSS license).  I can build against 3.14 while without dropping Java 8 support, and the jOOQ API seems compatible.  Since jOOQ is a `provided` dependency I don't believe there should be any issues if consumers want to use 3.15 or higher, but not sure if the modularization added in 3.15 causes any issues.

Other than that this overall looks good.  I'll probably bump to v2.0 given the major changes in Java and library versions.

**Comment by apptio-msobala** [comment]
@supercargo do you want to change it yourself?

**Comment by supercargo** [comment]
It's very minor, I already have a branch off your branch with that change which I pushed for the sake of tagging/releasing. It is (or will shortly be) available at
```
<dependency>
  <groupId>com.adamlewis</groupId>
  <artifactId>guice-persist-jooq</artifactId>
  <version>2.0.0-beta-1</version>
</dependency>
```
@apptio-msobala Could you try out `2.0.0-beta-1` and, if that works for you, I can merge your PR and my changes on top and re-publish without the `beta` designation.

**Comment by apptio-msobala** [comment]
@supercargo works as expected. Tested using both integration tests of transactions and in a running application.

**Comment by apptio-msobala** [comment]
@supercargo bump

**Comment by supercargo** [comment]
Thanks for your contributions @apptio-msobala!  v2.0.0 is released and will become available as maven central mirrors come up to date.

**Pull request merged**
